project:
  type: website

website:
  title: "codercops"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/anurag629
      - icon: twitter
        href: https://twitter.com/anurag_629
      - icon: linkedin
        href: https://www.linkedin.com/in/anurag629/
      - icon: instagram
        href: https://www.instagram.com/anurag_629/
  comments:
    giscus:
      repo: anurag629/codercops

format:
  html:
    theme: cosmo
    css: styles.css

editor: visual


